### ISSUE TITLE
Should `TempDir` impl `Deref<Path>`?

### ISSUE THREAD

**Issue by sgrif** [rust-lang-nursery/tempdir#10]
I always find it surprising when methods like `join` aren't present on `TempDir`. Is there any reason not to `impl Deref<Path> for TempDir` here?

**Comment by alexcrichton** [comment]
This is indeed a possibility! We decided to not use `Deref` for APIs like this because `TempDir` has semantics beyond that of `Path` and the addition of `Deref` means that the API surface area of `TempDir` can only very rarely grow (and only if we're quite careful).

Keeping a distinction allows the two to evolve independently and without fear basically.
