### ISSUE TITLE
Publish New Version

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/tempdir#41]
This is just a request for a new version of tempdir to be published with the updated version of `rand` (from https://github.com/rust-lang-nursery/tempdir/pull/40).

**Comment by otavio** [comment]
Also, the changes since the last release were nice and does improve the code so I strongly support this request.

**Comment by KodrAus** [comment]
Sorry for taking so long to circle around to this! Yes I think a release is long overdue. [It looks like we haven't changed the public API since `0.3.5`](https://github.com/rust-lang-nursery/tempdir/compare/1b5826e...master) but have probably shifted the minimum Rust version forward. I would like to release as `0.3.6` if we can.

**Comment by otavio** [comment]
It seems fine for me as well.

**Comment by KodrAus** [comment]
[`semverver`](https://github.com/rust-lang-nursery/rust-semverver) agrees:

```
$ cargo semver
       Fresh winapi v0.2.8
       Fresh winapi-build v0.1.1
       Fresh libc v0.2.36
       Fresh rand v0.4.2
       Fresh kernel32-sys v0.2.2
       Fresh remove_dir_all v0.3.0
       Fresh tempdir v0.3.5
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Fresh libc v0.2.36
       Fresh rand v0.3.20
       Fresh tempdir v0.3.5
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
version bump: 0.3.5 -> (patch) -> 0.3.6
```

I'll get this updated today.

**Comment by KodrAus** [comment]
I've published a new version of `tempdir`. See [the sparse release notes](https://github.com/rust-lang-nursery/tempdir/releases/tag/v0.3.6).

The only major thing here is that we've definitely moved the minimum `rustc` version forward to `1.13`. I think this is ok, because that release is over a year old and appears to be available in most package repositories.
